 
// Commands (ID_* and IDM_*) 
#define HID_INDICATOR_ICON                      0x10077
#define HID_INDICATOR_PROGRESS                  0x10078
#define HID_VIEW_PROPERTIESWND                  0x1007A
#define HID_EXPAND_ALL                          0x1007D
#define HID_SORTPROPERTIES                      0x10087
#define HID_PROPERTIES1                         0x10089
#define HID_SHEETSETUP_FORMFACTOR               0x100B0
#define HID_BACKGROUNDIMAGE_LOAD                0x100B1
#define HID_BACKGROUNDIMAGE_REMOVE              0x100B2
#define HID_VIEW_BACKGROUNDIMAGE                0x100B6
#define HID_VIEW_MODEINFORMATION                0x100B7
#define HID_FILE_SAVE_ALL                       0x100C7
#define HID_VIEW_OUTPUTWND                      0x100F7
#define HID_OP0                                 0x11010
#define HID_OP1                                 0x11011
#define HID_OP2                                 0x11012
#define HID_OP3                                 0x11013
#define HID_OP4                                 0x11014
#define HID_OP5                                 0x11015
#define HID_OP6                                 0x11016
#define HID_OP7                                 0x11017
#define HID_OP8                                 0x11018
#define HID_OP9                                 0x11019
#define HID_MODE_ANNOTATE                       0x11020
#define HID_MODE_CUT                            0x11021
#define HID_MODE_DIMENSION                      0x11022
#define HID_MODE_DRAW                           0x11023
#define HID_MODE_DRAW2                          0x11024
#define HID_MODE_EDIT                           0x11025
#define HID_MODE_NODAL                          0x11026
#define HID_MODE_NODALR                         0x11027
#define HID_MODE_TRAP                           0x11028
#define HID_MODE_TRAPR                          0x11029
#define HID_MODE_FIXUP                          0x1102A
#define HID_MODE_PRIMITIVE_EDIT                 0x1102B
#define HID_MODE_PRIMITIVE_MEND                 0x1102C
#define HID_MODE_GROUP_EDIT                     0x1102D
#define HID_MODE_LPD                            0x1102E
#define HID_MODE_POWER                          0x1102F
#define HID_MODE_PIPE                           0x11030
#define HID_CURSOR_DEFAULT                      0x11035
#define HID_CURSOR_SYMBOL                       0x11036
#define HID_SETUP_UNITS                         0x11037
#define HID_VIEW_REFRESH                        0x11038
#define HID_SETUP_SCALE                         0x11039
#define HID_FILE_TRACING                        0x1103F
#define HID_SETUP_NOTE                          0x11040
#define HID_RELATIVEMOVES_RIGHT                 0x11043
#define HID_RELATIVEMOVES_UP                    0x11044
#define HID_RELATIVEMOVES_LEFT                  0x11045
#define HID_RELATIVEMOVES_DOWN                  0x11046
#define HID_RELATIVEMOVES_IN                    0x11047
#define HID_RELATIVEMOVES_OUT                   0x11048
#define HID_RELATIVEMOVES_RIGHTROTATE           0x11049
#define HID_RELATIVEMOVES_UPROTATE              0x1104A
#define HID_RELATIVEMOVES_LEFTROTATE            0x1104B
#define HID_RELATIVEMOVES_DOWNROTATE            0x1104C
#define HID_TOOLS_GROUP_DELETE                  0x1104D
#define HID_TOOLS_PRIMITIVE_SNAPTO              0x1104E
#define HID_TOOLS_PRIMITIVE_SNAPTOENDPOINT      0x1104F
#define HID_TOOLS_GROUP_UNDELETE                0x11051
#define HID_SETUP_PENCOLOR                      0x11053
#define HID_SETUP_DIMLENGTH                     0x11056
#define HID_SETUP_DIMANGLE                      0x11057
#define HID_SETUP_PENSTYLE                      0x11058
#define HIDM_RETURN                             0x11064
#define HIDM_ESCAPE                             0x11065
#define HID_TOOLS_GROUP_BREAK                   0x1109E
#define HID_PRIM_BREAK                          0x1109F
#define HID_PENS_REMOVEUNUSEDSTYLES             0x110A4
#define HID_PENS_LOADCOLORS                     0x110A5
#define HID_PENS_UNLOADCOLORS                   0x110A6
#define HID_PENS_TRANSLATE                      0x110A7
#define HID_LAYERS_LOAD                         0x110A9
#define HID_LAYERS_UNLOAD                       0x110AA
#define HID_LAYERS_REMOVEEMPTY                  0x110AB
#define HID_LAYERS_STATICALL                    0x110AC
#define HID_LAYERS_ACTIVEALL                    0x110AD
#define HID_BLOCKS_LOAD                         0x110AF
#define HID_BLOCKS_UNLOAD                       0x110B0
#define HID_BLOCKS_REMOVEUNUSED                 0x110B1
#define HID_PENS_EDITSTYLES                     0x110B2
#define HID_TRACINGS_MAPALL                     0x110B4
#define HID_TRACINGS_VIEWALL                    0x110B5
#define HID_TRACINGS_CLOAKALL                   0x110B6
#define HID_PENS_EDITCOLORS                     0x110B7
#define HID_PENS_USEDEFAULTS                    0x110B8
#define HID_SETUP_SAVEPOINT                     0x110CE
#define HID_SETUP_GOTOPOINT                     0x110CF
#define HID_FILE_PLOT_QUARTER                   0x110D0
#define HID_MAINTENANCE_REMOVEDUPLICATES        0x110D4
#define HID_MAINTENANCE_REMOVEEMPTYNOTES        0x110D7
#define HID_MAINTENANCE_REMOVEEMPTYGROUPS       0x110D8
#define HID_FILE                                0x110DF
#define HID_HELP_CONTENTS                       0x110E1
#define HID_CLEAR_VIEWEDTRACINGS                0x110E2
#define HID_CLEAR_WORKINGLAYER                  0x110E3
#define HID_CLEAR_MAPPEDTRACINGS                0x110E4
#define HID_RESET_ALL                           0x110E5
#define HID_SETUP_FILL_HOLLOW                   0x110E6
#define HID_SETUP_FILL_SOLID                    0x110E7
#define HID_SETUP_FILL_PATTERN                  0x110E8
#define HID_SETUP_FILL_HATCH                    0x110E9
#define HID_PRIM_GOTOCENTERPOINT                0x110EE
#define HID_MODE_REVISE                         0x110EF
#define HID_MODE_LETTER                         0x110F0
#define HID_PRIM_PERPJUMP                       0x110F1
#define HID_PRIM_MODIFY_ATTRIBUTES              0x110F2
#define HID_HELP_KEY                            0x110F3
#define HID_FILE_PRINTCURRENTVIEW               0x110F5
#define HID_VIEW_ODOMETER                       0x110F6
#define HID_3DVIEWS_TOP                         0x110F8
#define HID_3DVIEWS_BOTTOM                      0x110F9
#define HID_3DVIEWS_FRONT                       0x110FA
#define HID_3DVIEWS_BACK                        0x110FB
#define HID_3DVIEWS_LEFT                        0x110FC
#define HID_3DVIEWS_RIGHT                       0x110FD
#define HID_3DVIEWS_ISOMETRIC                   0x11100
#define HID_VIEW_WIREFRAME                      0x11104
#define HID_TOOLS_GROUP_DELETELAST              0x11118
#define HID_PRIM_EXTRACTNUM                     0x11119
#define HID_PRIM_EXTRACTSTR                     0x1111A
#define HID_EDIT_TRAPCOPY                       0x1111C
#define HID_EDIT_TRAPCUT                        0x1111D
#define HID_EDIT_TRAPPASTE                      0x1111E
#define HID_FILE_RUN                            0x1112B
#define HID_VIEW_RENDERED                       0x11138
#define HID_VIEW_SOLID                          0x11139
#define HID_TOOLS_PRIMITVE_DELETE               0x11141
#define HID_VIEW_PARAMETERS                     0x11154
#define HID_EDIT_IMAGETOCLIPBOARD               0x11156
#define HID_EDIT_TRACE                          0x11158
#define HID_SETUP_MOUSEBUTTONS                  0x11162
#define HID_CURSOR_CROSSHAIR                    0x11163
#define HID_SETUP_OPTIONS_DRAW                  0x1119C
#define HID_SETUP_OPTIONS_EDIT                  0x1119D
#define HID_SETUP_OPTIONS_ANNOTATE              0x1119E
#define HID_SETUP_OPTIONS_2LINE                 0x1119F
#define HID_SETUP_OPTIONS_FIXUP                 0x111A0
#define HID_SETUP_OPTIONS_DIMENSION             0x111A1
#define HID_WINDOW_PAN_LEFT                     0x111B2
#define HID_WINDOW_PAN_UP                       0x111B4
#define HID_WINDOW_PAN_DOWN                     0x111B5
#define HID_VIEW_ZOOM                           0x111C6
#define HID_WINDOW_ZOOMIN                       0x111C7
#define HID_WINDOW_ZOOMOUT                      0x111C8
#define HID_WINDOW_NORMAL                       0x111C9
#define HID_WINDOW_PAN                          0x111CA
#define HID_TRACING_MAP                         0x111CC
#define HID_TRACING_VIEW                        0x111CD
#define HID_TRACING_CLOAK                       0x111CE
#define HID_TRACING_FUSE                        0x111CF
#define HID_LAYER_WORK                          0x111D0
#define HID_LAYER_ACTIVE                        0x111D1
#define HID_LAYER_STATIC                        0x111D2
#define HID_LAYER_HIDDEN                        0x111D3
#define HID_LAYER_MELT                          0x111D4
#define HID_LAYER_LAYERNAME                     0x111D5
#define HID_TRACING_TRACINGNAME                 0x111D6
#define HID_TRACING_OPEN                        0x111D7
#define HID_EDIT_TRAPQUIT                       0x111D9
#define HID_FILE_PLOT_FULL                      0x111DA
#define HID_FILE_PLOT_HALF                      0x111DB
#define HID_EDIT_TRAPWORK                       0x111DC
#define HID_EDIT_TRAPWORKANDACTIVE              0x111DE
#define HID_TRAPCOMMANDS_ADDGROUPS              0x111DF
#define HID_EDIT_TRAPDELETE                     0x111E1
#define HID_TRAPCOMMANDS_HIGHLIGHT              0x111E4
#define HID_TRAPCOMMANDS_COMPRESS               0x111E5
#define HID_TRAPCOMMANDS_EXPAND                 0x111E6
#define HID_TRAPCOMMANDS_INVERT                 0x111E7
#define HID_TRAPCOMMANDS_SQUARE                 0x111E8
#define HID_TRAPCOMMANDS_QUERY                  0x111E9
#define HID_TRAPCOMMANDS_FILTER                 0x111EA
#define HID_FILE_MANAGE                         0x111EB
#define HID_TRAPCOMMANDS_BLOCK                  0x111EC
#define HID_TRAPCOMMANDS_UNBLOCK                0x111EE
#define HID_TOOLS_GROUP_EXCHANGE                0x111EF
#define HID_EDIT_SEGTOWORK                      0x111F1
#define HID_VIEW_PENWIDTHS                      0x111F2
#define HID_SETUP_CONSTRAINTS_AXIS              0x111F7
#define HID_SETUP_CONSTRAINTS_GRID              0x111F8
#define HID_VIEW_TRUETYPEFONTS                  0x111FD
#define HID_VIEW_STATEINFORMATION               0x111FE
#define HID_CLEAR_ACTIVELAYERS                  0x111FF
#define HID_CLEAR_ALLLAYERS                     0x11200
#define HID_CLEAR_ALLTRACINGS                   0x11201
#define HID_EDIT_CF_GROUPS                      0x11208
#define HID_EDIT_CF_TEXT                        0x1120A
#define HID_EDIT_CF_IMAGE                       0x1120B
#define HID_VIEW_LIGHTING                       0x1120D
#define HID_WINDOW_PAN_RIGHT                    0x1120F
#define HID_WINDOW_BEST                         0x11210
#define HID_VIEW_WINDOW                         0x11211
#define HID_WINDOW_LAST                         0x11212
#define HID_WINDOW_SHEET                        0x11213
#define HID_CAMERA_ROTATELEFT                   0x11215
#define HID_CAMERA_ROTATERIGHT                  0x11216
#define HID_CAMERA_ROTATEUP                     0x11217
#define HID_CAMERA_ROTATEDOWN                   0x11218
#define HID_FILE_QUERY                          0x11219
#define HID_RELATIVEMOVES_ENG_RIGHT             0x1121A
#define HID_RELATIVEMOVES_ENG_DOWN              0x1121B
#define HID_RELATIVEMOVES_ENG_IN                0x1121C
#define HID_RELATIVEMOVES_ENG_OUT               0x1121D
#define HID_RELATIVEMOVES_ENG_LEFT              0x1121E
#define HID_RELATIVEMOVES_ENG_LEFTROTATE        0x1121F
#define HID_RELATIVEMOVES_ENG_RIGHTROTATE       0x11220
#define HID_RELATIVEMOVES_ENG_DOWNROTATE        0x11221
#define HID_RELATIVEMOVES_ENG_UP                0x11222
#define HID_RELATIVEMOVES_ENG_UPROTATE          0x11223
#define HID_SHIFT_RETURN                        0x11225
#define HID_VIEW_TOOLBARS                       0x11227
#define HID_VIEW_CUSTOMIZE                      0x11234
#define HID_MDI_TABBED                          0x11235
#define HID_WINDOW_MANAGER                      0x11236
#define HID_TOOLS_ENTRY                         0x1123C
#define HID_USER_TOOL1                          0x1123F
#define HID_USER_TOOL2                          0x11240
#define HID_USER_TOOL3                          0x11241
#define HID_USER_TOOL4                          0x11242
#define HID_USER_TOOL5                          0x11243
#define HID_USER_TOOL6                          0x11244
#define HID_USER_TOOL7                          0x11245
#define HID_USER_TOOL8                          0x11246
#define HID_USER_TOOL9                          0x11247
#define HID_USER_TOOL10                         0x11248
#define HID_MENU_ITEM1                          0x11249
#define HID_MENU_ITEM2                          0x1124A
#define HID_MENU_ITEM3                          0x1124B
#define HID_MENU_DIR1                           0x1124C
#define HID_MENU_DIR2                           0x1124D
#define HID_MENU_DIR3                           0x1124E
#define HID_VIEW_FULLSCREEN                     0x11252
#define HID_VIEW_USER_TOOLBAR1                  0x11253
#define HID_VIEW_USER_TOOLBAR2                  0x11254
#define HID_VIEW_USER_TOOLBAR3                  0x11255
#define HID_VIEW_USER_TOOLBAR4                  0x11256
#define HID_VIEW_USER_TOOLBAR5                  0x11257
#define HID_VIEW_USER_TOOLBAR6                  0x11258
#define HID_VIEW_USER_TOOLBAR7                  0x11259
#define HID_VIEW_USER_TOOLBAR8                  0x1125A
#define HID_VIEW_USER_TOOLBAR9                  0x1125B
#define HID_VIEW_USER_TOOLBAR10                 0x1125C
#define HID_SETUP_LAYERPROPERTIES               0x1127D
#define HID_EDIT_FIND_COMBO                     0x1129B
#define HID_VIEW_APPLOOK_OFF_2007_BLUE          0x112C6
#define HID_VIEW_APPLOOK_OFF_2007_BLACK         0x112C7
#define HID_VIEW_APPLOOK_OFF_2007_AQUA          0x112C8
#define HID_VIEW_APPLOOK_OFF_2007_SILVER        0x112C9
#define HID_VIEW_APPLOOK_WINDOWS_7              0x112CA
#define HID_DRAW_MODE_OPTIONS                   0x113EC
#define HID_DRAW_MODE_POINT                     0x113ED
#define HID_DRAW_MODE_LINE                      0x113EE
#define HID_DRAW_MODE_POLYGON                   0x113EF
#define HID_DRAW_MODE_QUAD                      0x113F0
#define HID_DRAW_MODE_ARC                       0x113F1
#define HID_DRAW_MODE_ELLIPSE                   0x113F2
#define HID_DRAW_MODE_CIRCLE                    0x113F3
#define HID_DRAW_MODE_BSPLINE                   0x113F4
#define HID_DRAW_MODE_INSERT                    0x113F5
#define HID_DRAW_MODE_RETURN                    0x113F6
#define HID_DRAW_MODE_ESCAPE                    0x113F7
#define HID_DRAW_MODE_SHIFT_RETURN              0x113F8
#define HID_DRAW2_MODE_OPTIONS                  0x11450
#define HID_DRAW2_MODE_JOIN                     0x11451
#define HID_DRAW2_MODE_WALL                     0x11452
#define HID_DRAW2_MODE_3                        0x11453
#define HID_DRAW2_MODE_4                        0x11454
#define HID_DRAW2_MODE_5                        0x11455
#define HID_DRAW2_MODE_6                        0x11456
#define HID_DRAW2_MODE_7                        0x11457
#define HID_DRAW2_MODE_8                        0x11458
#define HID_DRAW2_MODE_9                        0x11459
#define HID_DRAW2_MODE_RETURN                   0x1145A
#define HID_DRAW2_MODE_ESCAPE                   0x1145B
#define HID_DRAW2_MODE_SHIFT_RETURN             0x1145C
#define HID_ANNOTATE_MODE_OPTIONS               0x114B4
#define HID_ANNOTATE_MODE_1                     0x114B5
#define HID_ANNOTATE_MODE_LINE                  0x114B6
#define HID_ANNOTATE_MODE_ARROW                 0x114B7
#define HID_ANNOTATE_MODE_BUBBLE                0x114B8
#define HID_ANNOTATE_MODE_HOOK                  0x114B9
#define HID_ANNOTATE_MODE_UNDERLINE             0x114BA
#define HID_ANNOTATE_MODE_BOX                   0x114BB
#define HID_ANNOTATE_MODE_CUT_IN                0x114BC
#define HID_ANNOTATE_MODE_CONSTRUCTION_LINE     0x114BD
#define HID_ANNOTATE_MODE_RETURN                0x114BE
#define HID_ANNOTATE_MODE_ESCAPE                0x114BF
#define HID_ANNOTATE_MODE_SHIFT_RETURN          0x114C0
#define HID_EDIT_MODE_OPTIONS                   0x11518
#define HID_EDIT_MODE_PIVOT                     0x11519
#define HID_EDIT_MODE_ROTCCW                    0x1151A
#define HID_EDIT_MODE_ROTCW                     0x1151B
#define HID_EDIT_MODE_MOVE                      0x1151C
#define HID_EDIT_MODE_COPY                      0x1151D
#define HID_EDIT_MODE_FLIP                      0x1151E
#define HID_EDIT_MODE_REDUCE                    0x1151F
#define HID_EDIT_MODE_ENLARGE                   0x11520
#define HID_EDIT_MODE_9                         0x11521
#define HID_EDIT_MODE_RETURN                    0x11522
#define HID_EDIT_MODE_ESCAPE                    0x11523
#define HID_EDIT_MODE_SHIFT_RETURN              0x11524
#define HID_TRAP_MODE_REMOVE_ADD                0x1157C
#define HID_TRAP_MODE_POINT                     0x1157D
#define HID_TRAP_MODE_STITCH                    0x1157E
#define HID_TRAP_MODE_3                         0x1157F
#define HID_TRAP_MODE_FIELD                     0x11580
#define HID_TRAP_MODE_LAST                      0x11581
#define HID_TRAP_MODE_ENGAGE                    0x11582
#define HID_TRAP_MODE_7                         0x11583
#define HID_TRAP_MODE_MENU                      0x11584
#define HID_TRAP_MODE_MODIFY                    0x11585
#define HID_TRAP_MODE_RETURN                    0x11586
#define HID_TRAP_MODE_ESCAPE                    0x11587
#define HID_TRAP_MODE_SHIFT_RETURN              0x11588
#define HID_TRAPR_MODE_REMOVE_ADD               0x115E0
#define HID_TRAPR_MODE_POINT                    0x115E1
#define HID_TRAPR_MODE_STITCH                   0x115E2
#define HID_TRAPR_MODE_3                        0x115E3
#define HID_TRAPR_MODE_FIELD                    0x115E4
#define HID_TRAPR_MODE_LAST                     0x115E5
#define HID_TRAPR_MODE_ENGAGE                   0x115E6
#define HID_TRAPR_MODE_7                        0x115E7
#define HID_TRAPR_MODE_MENU                     0x115E8
#define HID_TRAPR_MODE_MODIFY                   0x115E9
#define HID_TRAPR_MODE_RETURN                   0x115EA
#define HID_TRAPR_MODE_ESCAPE                   0x115EB
#define HID_TRAPR_MODE_SHIFT_RETURN             0x115EC
#define HID_DIMENSION_MODE_OPTIONS              0x11644
#define HID_DIMENSION_MODE_ARROW                0x11645
#define HID_DIMENSION_MODE_LINE                 0x11646
#define HID_DIMENSION_MODE_DLINE                0x11647
#define HID_DIMENSION_MODE_DLINE2               0x11648
#define HID_DIMENSION_MODE_EXTEN                0x11649
#define HID_DIMENSION_MODE_RADIUS               0x1164A
#define HID_DIMENSION_MODE_DIAMETER             0x1164B
#define HID_DIMENSION_MODE_ANGLE                0x1164C
#define HID_DIMENSION_MODE_CONVERT              0x1164D
#define HID_DIMENSION_MODE_RETURN               0x1164E
#define HID_DIMENSION_MODE_ESCAPE               0x1164F
#define HID_DIMENSION_MODE_SHIFT_RETURN         0x11650
#define HID_CUT_MODE_OPTIONS                    0x116A8
#define HID_CUT_MODE_TORCH                      0x116A9
#define HID_CUT_MODE_SLICE                      0x116AA
#define HID_CUT_MODE_3                          0x116AB
#define HID_CUT_MODE_FIELD                      0x116AC
#define HID_CUT_MODE_5                          0x116AD
#define HID_CUT_MODE_6                          0x116AE
#define HID_CUT_MODE_CLIP                       0x116AF
#define HID_CUT_MODE_8                          0x116B0
#define HID_CUT_MODE_DIVIDE                     0x116B1
#define HID_CUT_MODE_RETURN                     0x116B2
#define HID_CUT_MODE_ESCAPE                     0x116B3
#define HID_CUT_MODE_SHIFT_RETURN               0x116B4
#define HID_FIXUP_MODE_OPTIONS                  0x1170C
#define HID_FIXUP_MODE_REFERENCE                0x1170D
#define HID_FIXUP_MODE_MEND                     0x1170E
#define HID_FIXUP_MODE_CHAMFER                  0x1170F
#define HID_FIXUP_MODE_FILLET                   0x11710
#define HID_FIXUP_MODE_SQUARE                   0x11711
#define HID_FIXUP_MODE_PARALLEL                 0x11712
#define HID_FIXUP_MODE_7                        0x11713
#define HID_FIXUP_MODE_8                        0x11714
#define HID_FIXUP_MODE_9                        0x11715
#define HID_FIXUP_MODE_RETURN                   0x11716
#define HID_FIXUP_MODE_ESCAPE                   0x11717
#define HID_FIXUP_MODE_SHIFT_RETURN             0x11718
#define HID_NODAL_MODE_ADDREMOVE                0x11770
#define HID_NODAL_MODE_POINT                    0x11771
#define HID_NODAL_MODE_LINE                     0x11772
#define HID_NODAL_MODE_AREA                     0x11773
#define HID_NODAL_MODE_MOVE                     0x11774
#define HID_NODAL_MODE_COPY                     0x11775
#define HID_NODAL_MODE_TOLINE                   0x11776
#define HID_NODAL_MODE_TOPOLYGON                0x11777
#define HID_NODAL_MODE_EMPTY                    0x11778
#define HID_NODAL_MODE_ENGAGE                   0x11779
#define HID_NODAL_MODE_RETURN                   0x1177A
#define HID_NODAL_MODE_ESCAPE                   0x1177B
#define HID_NODAL_MODE_SHIFT_RETURN             0x1177C
#define HID_PIPE_MODE_OPTIONS                   0x117D4
#define HID_PIPE_MODE_1                         0x117D5
#define HID_PIPE_MODE_LINE                      0x117D6
#define HID_PIPE_MODE_FITTING                   0x117D7
#define HID_PIPE_MODE_DROP                      0x117D8
#define HID_PIPE_MODE_RISE                      0x117D9
#define HID_PIPE_MODE_6                         0x117DA
#define HID_PIPE_MODE_7                         0x117DB
#define HID_PIPE_MODE_SYMBOL                    0x117DC
#define HID_PIPE_MODE_WYE                       0x117DD
#define HID_PIPE_MODE_RETURN                    0x117DE
#define HID_PIPE_MODE_ESCAPE                    0x117DF
#define HID_PIPE_MODE_SHIFT_RETURN              0x117E0
#define HID_POWER_MODE_OPTIONS                  0x11838
#define HID_POWER_MODE_1                        0x11839
#define HID_POWER_MODE_CIRCUIT                  0x1183A
#define HID_POWER_MODE_3                        0x1183B
#define HID_POWER_MODE_GROUND                   0x1183C
#define HID_POWER_MODE_HOT                      0x1183D
#define HID_POWER_MODE_SWITCH                   0x1183E
#define HID_POWER_MODE_NEUTRAL                  0x1183F
#define HID_POWER_MODE_HOME                     0x11840
#define HID_POWER_MODE_9                        0x11841
#define HID_POWER_MODE_RETURN                   0x11842
#define HID_POWER_MODE_ESCAPE                   0x11843
#define HID_POWER_MODE_SHIFT_RETURN             0x11844
#define HID_LPD_MODE_OPTIONS                    0x1189C
#define HID_LPD_MODE_JOIN                       0x1189D
#define HID_LPD_MODE_DUCT                       0x1189E
#define HID_LPD_MODE_TRANSITION                 0x1189F
#define HID_LPD_MODE_TAP                        0x118A0
#define HID_LPD_MODE_ELL                        0x118A1
#define HID_LPD_MODE_TEE                        0x118A2
#define HID_LPD_MODE_UP_DOWN                    0x118A3
#define HID_LPD_MODE_8                          0x118A4
#define HID_LPD_MODE_SIZE                       0x118A5
#define HID_LPD_MODE_RETURN                     0x118A6
#define HID_LPD_MODE_ESCAPE                     0x118A7
#define HID_LPD_MODE_SHIFT_RETURN               0x118A8
 
// Prompts (IDP_*) 
#define HIDP_OLE_INIT_FAILED                    0x30064
 
// Resources (IDR_*) 
#define HIDR_MAINFRAME                          0x20065
#define HIDR_MAINFRAME_256                      0x20066
#define HIDR_AESYSTYPE                          0x20067
#define HIDR_TRACINGTYPE                        0x20068
#define HIDR_LAYER                              0x2006A
#define HIDR_WINDOW                             0x2006B
#define HIDR_TRAP                               0x20076
#define HIDR_PEGSTROKEFONT                      0x2008E
#define HIDR_TRACING                            0x200BB
#define HIDR_OUTPUT_POPUP                       0x200BC
#define HIDR_CONTEXT_MENU                       0x200BD
#define HIDR_POPUP_TOOLBAR                      0x200BF
#define HIDR_POPUP_MDITABS                      0x200C2
#define HIDR_PROPERTIES                         0x200C3
#define HIDR_MENU_ARGS                          0x200C5
#define HIDR_MENU_DIRS                          0x200C6
#define HIDR_TRAPR_MODE                         0x2010B
#define HIDR_TRAP_MODE                          0x2010C
#define HIDR_EDIT_MODE                          0x2010D
#define HIDR_DRAW_MODE                          0x2010E
#define HIDR_ANNOTATE_MODE                      0x2010F
#define HIDR_PIPE_MODE                          0x20110
#define HIDR_POWER_MODE                         0x20111
#define HIDR_DRAW2_MODE                         0x20112
#define HIDR_DIMENSION_MODE                     0x20113
#define HIDR_CUT_MODE                           0x20114
#define HIDR_FIXUP_MODE                         0x20115
#define HIDR_NODAL_MODE                         0x20116
#define HIDR_NODALR_MODE                        0x20117
#define HIDR_LPD_MODE                           0x20118
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_PROPPAGE_SMALL                     0x20066
#define HIDD_DIALOGBAR                          0x20067
#define HIDD_SETUP_COLOR                        0x20079
#define HIDD_UNITS                              0x2007B
#define HIDD_FILE_BLOCK                         0x2007C
#define HIDD_SETUP_PENSTYLE                     0x2007E
#define HIDD_SET_LENGTH                         0x20088
#define HIDD_PIPE_SYMBOL                        0x2008A
#define HIDD_PIPE_OPTIONS                       0x2008B
#define HIDD_SETUP_CONSTRAINTS_AXIS             0x2008C
#define HIDD_SETUP_CONSTRAINTS_GRID             0x2008D
#define HIDD_SELECT_ISOMETRIC_VIEW              0x2008F
#define HIDD_TRACING_EX                         0x20091
#define HIDD_DLGPROC_LPD_OPTIONS                0x20092
#define HIDD_SETUP_NOTE                         0x20094
#define HIDD_SET_TEXT                           0x20095
#define HIDD_ANNOTATE_OPTIONS                   0x20096
#define HIDD_EDIT_TRAPCOMMANDS_QUERY            0x20097
#define HIDD_FIXUP_OPTIONS                      0x20098
#define HIDD_HOME_POINT_EDIT                    0x20099
#define HIDD_SET_ANGLE                          0x2009A
#define HIDD_SETUP_HATCH                        0x2009B
#define HIDD_TRAP_MODIFY                        0x2009C
#define HIDD_HOME_POINT_GO                      0x2009D
#define HIDD_TRAP_FILTER                        0x2009E
#define HIDD_VIEWLIGHTING                       0x200A0
#define HIDD_INSERT_BLOCK                       0x200A2
#define HIDD_VIEW_PARAMETERS                    0x200A3
#define HIDD_PASTE_POSITION                     0x200A4
#define HIDD_MOUSEKEYS                          0x200A5
#define HIDD_DRAW_OPTIONS                       0x200A6
#define HIDD_GET_LAYER_NAME                     0x200A7
#define HIDD_SET_SCALE                          0x200A8
#define HIDD_FILE_MANAGE                        0x200A9
#define HIDD_ADD_NOTE                           0x200AA
#define HIDD_EDIT_OPTIONS                       0x200AB
#define HIDD_VIEW_ZOOM                          0x200AC
#define HIDD_PRINT_EX                           0x200B8
#define HIDD_LAYER_PROPERTIES_MANAGER           0x2011E
#define HIDD_LAYER_PROPERTIES_LINEWEIGHT        0x2012C
#define HIDD_LINEWEIGHT                         0x2012D
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#ifndef __AFX_HH_H__
#define __AFX_HH_H__

#pragma once

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, off)
#endif

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, on)
#endif

#endif // __AFX_HH_H__
